# Generated by Django 6.0.1 on 2026-03-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="ticket",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("em_andamento", "Em andamento"),
                    ("resolvido", "Resolvido"),
                    ("fechado", "Fechado"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
    ]
