# Generated by Django 6.0.1 on 2026-03-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0004_resposta_chamado"),
    ]

    operations = []
