# Generated by Django 6.0.1 on 2026-03-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0005_adicionar_respostas"),
        ("chamados", "000X_adicionar_respostas"),
    ]

    operations = []
