# Generated by Django 6.0.1 on 2026-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0006_merge_20260310_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="anexo",
            field=models.FileField(blank=True, null=True, upload_to="anexos/"),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("em_andamento", "Em andamento"),
                    ("aguardando", "Aguardando cliente"),
                    ("resolvido", "Resolvido"),
                    ("fechado", "Fechado"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
    ]
