# Generated by Django 6.0.1 on 2026-03-23 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0007_chamado_anexo_alter_chamado_prioridade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("notebook", "Notebook"),
                            ("carregador", "Carregador"),
                            ("mouse", "Mouse"),
                            ("monitor", "Monitor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("patrimonio", models.CharField(max_length=50, unique=True)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="perfil",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("colaborador", "Colaborador"),
                    ("tecnico", "Técnico"),
                    ("admin", "Administrador"),
                ],
                default="colaborador",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("saida", "Saída"), ("entrada", "Entrada")],
                        max_length=10,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chamados.equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RespostaChamado",
        ),
    ]
