# Generated by Django 6.0.1 on 2026-08-04 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0008_equipamento_alter_perfil_tipo_movimentacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("gestor", models.CharField(blank=True, max_length=150)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("site", models.URLField(blank=True)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("contato", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("endereco", models.TextField(blank=True)),
                ("observacao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("endereco", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="chamado",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["patrimonio"],
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="movimentacao",
            options={"ordering": ["-data"]},
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="disponivel",
        ),
        migrations.AddField(
            model_name="equipamento",
            name="armazenamento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipamentos_recebidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="equipamento",
            name="data_compra",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="data_devolucao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="data_entrega",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="endereco_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="endereco_mac",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="equipamentos/"),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="garantia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="marca",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="memoria",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="modelo",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="nota_fiscal",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="numero_serie",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="observacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="patrimonio_antigo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="processador",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcode/"),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="sistema_operacional",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("disponivel", "Disponível"),
                    ("em_uso", "Em Uso"),
                    ("manutencao", "Em Manutenção"),
                    ("defeito", "Com Defeito"),
                    ("reservado", "Reservado"),
                    ("baixado", "Baixado"),
                ],
                default="disponivel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="colaborador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_colaborador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("em_andamento", "Em andamento"),
                    ("aguardando", "Aguardando Cliente"),
                    ("resolvido", "Resolvido"),
                    ("fechado", "Fechado"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="ticket",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("notebook", "Notebook"),
                    ("desktop", "Desktop"),
                    ("monitor", "Monitor"),
                    ("mouse", "Mouse"),
                    ("teclado", "Teclado"),
                    ("headset", "Headset"),
                    ("impressora", "Impressora"),
                    ("tablet", "Tablet"),
                    ("celular", "Celular"),
                    ("switch", "Switch"),
                    ("roteador", "Roteador"),
                    ("servidor", "Servidor"),
                    ("nobreak", "Nobreak"),
                    ("carregador", "Carregador"),
                    ("outro", "Outro"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="equipamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="chamados.equipamento",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("saida", "Saída"),
                    ("transferencia", "Transferência"),
                    ("devolucao", "Devolução"),
                    ("emprestimo", "Empréstimo"),
                    ("manutencao", "Manutenção"),
                    ("defeito", "Defeito"),
                    ("baixa", "Baixa Patrimonial"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.categoria",
            ),
        ),
        migrations.CreateModel(
            name="Defeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("analise", "Em análise"),
                            ("resolvido", "Resolvido"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defeitos",
                        to="chamados.equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="equipamento",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.departamento",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.departamento",
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="fabricante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.fabricante",
            ),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.fornecedor",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="chamados.equipamento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.AddField(
            model_name="equipamento",
            name="localizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.localizacao",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="localizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chamados.localizacao",
            ),
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=150)),
                ("tecnico", models.CharField(blank=True, max_length=150)),
                ("problema", models.TextField()),
                ("solucao", models.TextField(blank=True)),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_envio", models.DateField()),
                ("data_retorno", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("andamento", "Em andamento"),
                            ("aguardando", "Aguardando Peças"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("laudo", models.FileField(blank=True, null=True, upload_to="laudos/")),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="chamados.equipamento",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RespostaChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                (
                    "anexo",
                    models.FileField(blank=True, null=True, upload_to="respostas/"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="chamados.chamado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="TermoResponsabilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("assinado", models.BooleanField(default=False)),
                ("pdf", models.FileField(blank=True, null=True, upload_to="termos/")),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termos_recebidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregue_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="termos_entregues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chamados.equipamento",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_entrega"],
            },
        ),
    ]
