# Generated by Django 6.0.1 on 2026-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0009_categoria_departamento_fabricante_fornecedor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("rede", "Rede / Internet"),
                    ("email", "Email"),
                    ("sistema_interno", "Sistema Interno"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
