# Generated by Django 6.0.1 on 2026-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0011_notificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="foto",
            field=models.FileField(blank=True, null=True, upload_to="equipamentos/"),
        ),
    ]
