# Generated by Django 6.0.1 on 2026-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0012_alter_equipamento_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamento",
            name="imagem_pc",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipamentos/imagens/"
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfis/"),
        ),
    ]
